server {
    listen 80;
    server_name onesearch.blog www.onesearch.blog;

    # Certbot uses this path to verify domain ownership
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Forward all other traffic to Flask
    location / {
        proxy_pass http://app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}