export const EMOJI_OPTIONS = [
  { emoji: '🔥', label: 'Fire' },
  { emoji: '🧘', label: 'Zen' },
  { emoji: '💰', label: 'Money' },
  { emoji: '🦆', label: 'Duck' },
  { emoji: '🌮', label: 'Taco' },
  { emoji: '👔', label: 'Corporate' },
  { emoji: '🕳️', label: 'Void' },
  { emoji: '🧀', label: 'Cheese' },
  { emoji: '🚀', label: 'Rocket' },
  { emoji: '🪴', label: 'Plant' },
  { emoji: '⚰️', label: 'Coffin' },
  { emoji: '🎩', label: 'Top Hat' },
  { emoji: '🐌', label: 'Snail' },
  { emoji: '🌪️', label: 'Tornado' },
  { emoji: '🧲', label: 'Magnet' },
  { emoji: '🦷', label: 'Tooth' },
  { emoji: '🎻', label: 'Violin' },
  { emoji: '🧊', label: 'Ice' },
  { emoji: '🪤', label: 'Trap' },
  { emoji: '🐧', label: 'Penguin' },
  { emoji: '🎯', label: 'Bullseye' },
  { emoji: '🧸', label: 'Teddy' },
  { emoji: '🪞', label: 'Mirror' },
  { emoji: '🌵', label: 'Cactus' },
  { emoji: '🎪', label: 'Circus' },
  { emoji: '🦠', label: 'Bacteria' },
  { emoji: '🧪', label: 'Lab' },
  { emoji: '🎭', label: 'Theatre' },
  { emoji: '🌑', label: 'Dark Moon' },
  { emoji: '🦴', label: 'Bone' },
]
